server:
    port: 20015
    context-path: #/liuzh/

logging:
#    config:
#      classpath: logback.xml
#    path: /Users/fengxiaotx/logs
    level: debug
    file: log.log

spring:
#    freemarker.prefer-file-system-access: false
    datasource:
        url: jdbc:mysql://localhost:3306/score?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 600
        minIdle: 1
        timeBetweenEvictionRunsMillis: 600
        minEvictableIdleTimeMillis: 3000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /WEB-INF/jsp
            suffix: .jsp
#    freemarker:
#        cache: false
#        request-context-attribute: request
#        content-type: text/html
    messages:
        encoding: utf-8
    http:
        encoding:
            charset: UTF-8
            enabled: true
    redis:
          host: 172.16.7.30
          password:
          port: 6379
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 300
            max-wait: 10000
          timeout: 100000


#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
